question_data = [{"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "A person can get sunburned on a cloudy day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "The most frequent subconscious activity repeated by the human body is blinking.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science &amp; Nature",
                  "question": "The Neanderthals were a direct ancestor of modern humans.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Science &amp; Nature",
                  "question": "The chemical element Lithium is named after the country of Lithuania.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Science &amp; Nature",
                  "question": "The value of one Calorie is different than the value of one calorie.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
